"""Terjemahan Inggris. Kunci = teks Indonesia di template/kode."""
EN = {
    # --- navigasi & kerangka ---
    "Bulan": "Month",
    "Kantong": "Pockets",
    "Laporan": "Report",
    "Ringkasan": "Overview",
    "Aset": "Assets",
    "Setelan": "Settings",
    "Keluar": "Sign out",
    "Masuk": "Sign in",
    "Ganti tema": "Switch theme",
    "Ganti tema terang/gelap": "Switch light/dark theme",
    "Tutup": "Close",
    "Batal": "Cancel",
    "Hapus": "Delete",
    "Simpan": "Save",
    "Tambah": "Add",
    "Edit": "Edit",
    "Rapikan": "Clean up",
    "Pindah": "Transfer",
    "Cash · pockets · assets": "Cash · pockets · assets",
    "Personal finance tracker": "Personal finance tracker",

    # --- login ---
    "Password": "Password",
    "Tampilkan password": "Show password",
    "Password salah.": "Wrong password.",
    "Password belum di-set. Isi": "No password set yet. Put",
    "di file": "in",
    "lalu restart.": "then restart.",
    "Video ·": "Video ·",

    # --- halaman bulan ---
    "Sisa kas": "Cash left",
    "Sisa kas ·": "Cash left ·",
    "Sisa kas terkini": "Cash on hand",
    "vs saldo awal": "vs opening balance",
    "vs bulan lalu": "vs last month",
    "Pemasukan": "Income",
    "Pengeluaran": "Expense",
    "Transfer": "Transfer",
    "Dana darurat": "Emergency fund",
    "Total aset": "Total assets",
    "Total assets": "Total assets",
    "Total aset ·": "Total assets ·",
    "Kekayaan bersih": "Net worth",
    "Pemasukan dan pengeluaran 6 bulan terakhir": "Income and expense, last 6 months",
    "Pemasukan dan pengeluaran per bulan": "Income and expense by month",
    "Pemasukan baru": "New income",
    "Pengeluaran baru": "New expense",
    "Template rutin baru": "New recurring template",
    "Kantong baru": "New pocket",
    "Kategori baru": "New category",
    "Jumlah": "Amount",
    "Kategori": "Category",
    "Deskripsi": "Description",
    "Keterangan": "Note",
    "Tanggal": "Date",
    "Tanggal (1–28)": "Day of month (1–28)",
    "Status": "Status",
    "Jenis": "Type",
    "Nama": "Name",
    "Urutan": "Order",
    "Sudah dibayar": "Paid",
    "Belum dibayar": "Not paid yet",
    "belum dibayar": "not paid",
    "belum": "unpaid",
    "Masuk ke": "Goes into",
    "Dari kantong": "From pocket",
    "Ke kantong": "To pocket",
    "Ke kantong (transfer)": "To pocket (transfer)",
    "Dari": "From",
    "Ke": "To",
    "Kas": "Cash",
    "kas": "cash",
    "Tabungan": "Savings",
    "Investasi": "Investments",
    "investasi": "investments",
    "ditabung": "saved",
    "· ditabung": "· saved",
    "· investasi": "· investments",
    "· tabungan": "· savings",
    "· aset": "· assets",
    "· nilai": "· value",
    "Ke tabungan & investasi": "To savings & investments",
    "Sumber / deskripsi": "Source / description",
    "mis. Gaji John, bonus, proyek": "e.g. John's salary, bonus, side project",
    "mis. bensin, arisan, makan siang": "e.g. fuel, groceries, lunch",
    "mis. KPR rumah": "e.g. mortgage",
    "mis. setor tabungan, top up": "e.g. move to savings, top up",
    "mis. BCA, Dana Darurat": "e.g. BCA, Emergency fund",
    "mis. BCA, Reksadana": "e.g. BCA, Mutual fund",
    "mis. Langganan, Hewan peliharaan": "e.g. Subscriptions, Pets",
    "BMRI, BTC, IDLE": "BMRI, BTC, IDLE",
    "Belum ada pengeluaran.": "No expenses yet.",
    "Belum ada pengeluaran bulan ini.": "No expenses this month.",
    "Belum ada pemasukan.": "No income yet.",
    "Ketuk “+ Pemasukan” di bawah.": "Tap “+ Income” below.",
    "Ketuk “− Pengeluaran” di bawah untuk mencatat.": "Tap “− Expense” below to record one.",
    "Tidak ada perpindahan bulan ini.": "No transfers this month.",
    "Menabung, setor dana darurat, atau isi kantong lain lewat “⇄ Transfer”.":
        "Save, top up the emergency fund, or fill another pocket with “⇄ Transfer”.",
    "Bulan ini masih kosong.": "This month is still empty.",
    "Isi dari template rutin (KPR, tagihan, gaji) lalu sesuaikan.":
        "Fill it from your recurring templates (mortgage, bills, salary), then adjust.",
    "Isi bulan ini": "Fill this month",
    "Isi yang belum tercatat": "Add what is missing",
    "Belum tercatat": "Not recorded yet",
    "dari template rutin": "from recurring templates",
    "Semua template rutin sudah tercatat.": "Every recurring template is already recorded.",
    "biasanya tgl": "usually on day",
    "tgl": "day",
    "Total": "Total",
    "entri": "entries",
    "transaksi": "transactions",
    "kategori": "categories",
    "bulan ini": "this month",
    "per bulan": "per month",
    "rata-rata": "average",
    "sisa": "left",
    "dari": "of",
    "vs": "vs",
    "vs rata²": "vs avg",
    "tidak ada mutasi": "no movement",
    "— tanpa kategori —": "— no category —",
    "opsional": "optional",
    "Ini transfer?": "Is this a transfer?",
    "Jadikan transfer": "Make it a transfer",
    "Ubah jadi transfer": "Turn into a transfer",
    "Uang ini pindah kantong, bukan belanja. Setelah diubah, nilainya keluar\n    dari hitungan pengeluaran/pemasukan bulan ini.":
        "This money moves between pockets, it is not spending. Once converted it drops out of\n    this month's income and expense totals.",
    "Uang pindah tempat, bukan belanja — tidak masuk hitungan pengeluaran bulan ini.":
        "Money moved, nothing was spent — it stays out of this month's expense total.",
    "Pindah antar kantong": "Move between pockets",

    # --- dashboard / ringkasan ---
    "Dashboard": "Dashboard",
    "Cari deskripsi / kategori di bulan ini…": "Search description / category this month…",
    "Hapus pencarian": "Clear search",
    "Sisa bulan ini": "Net this month",
    "masuk − keluar": "in − out",
    "masuk vs keluar · ketuk untuk pindah": "in vs out · tap to switch",
    "bulan · masuk vs keluar": "months · in vs out",
    "Pengeluaran per kategori": "Expense by category",
    "Entri terbesar": "Largest entries",
    "Per bulan": "By month",
    "Per kantong": "By pocket",
    "Dana darurat & assets": "Emergency fund & assets",
    "posisi akhir bulan": "end-of-month position",
    "posisi awal": "opening position",
    "saldo awal": "opening balance",
    "Saldo awal": "Opening balance",
    "Saldo awal = posisi sebelum bulan pertama yang kamu catat. Saldo berjalan dihitung dari transaksi.":
        "Opening balance = where you stood before the first month you record. Running balances come from transactions.",
    "Pilih bulan": "Pick a month",
    "Pilih tanggal": "Pick a date",
    "Tren total aset": "Total assets trend",

    # --- laporan ---
    "Kesehatan keuangan": "Financial health",
    "dihitung dari transaksimu sendiri": "computed from your own transactions",
    "Sorotan": "Highlights",
    "dibanding rata-rata 3 bulan": "against the 3-month average",
    "Saran": "Suggestions",
    "maksimal empat, yang paling berdampak": "at most four, the ones that matter",
    "bulan ini vs rata-rata 3 bulan": "this month vs the 3-month average",
    "Tentang laporan ini": "About this report",
    "Disusun dari transaksimu sendiri dengan aturan tetap — tidak ada data yang\n  dikirim ke mana pun. Dibuat":
        "Built from your own transactions with fixed rules — nothing is sent anywhere. Generated",
    "lalu disimpan, jadi membukanya lagi tidak menghitung ulang.":
        "and then stored, so opening it again does not recompute it.",
    "Buat ulang": "Rebuild",
    "kalau kamu baru mengubah transaksi bulan ini.": "if you just changed this month's transactions.",
    "Rincian": "Details",
    "Lihat kategori": "See categories",
    "Perbarui": "Update",

    # --- perapihan / review ---
    "Perapihan": "Clean-up",
    "transaksi impor yang kategorinya perlu dicek": "imported transactions whose category needs a check",
    "Buka layar perapihan": "Open the clean-up screen",
    "aplikasi menyarankan kategori dari deskripsi; kamu yang memutuskan":
        "the app suggests a category from the description; you decide",
    "Kenapa ini ada": "Why this exists",
    "Cara kerjanya": "How it works",
    "Transaksi hasil impor dari spreadsheet belum punya kategori yang benar —\n  dulu semuanya masuk “OTHER”. Aplikasi menebak kategorinya dari deskripsi dan menandainya":
        "Transactions imported from the spreadsheet have no proper category —\n  everything used to land in “OTHER”. The app guesses one from the description and marks it",
    "; tebakan itu": "; that guess is",
    "tersimpan sampai kamu menekan Simpan.\n  Periksa satu bulan, simpan, lanjut ke bulan berikutnya.":
        "not saved until you press Save.\n  Check one month, save, move on to the next.",
    "Bulan yang perlu dirapikan": "Months that need a clean-up",
    "transaksi menunggu": "transactions waiting",
    "transaksi bulan ini perlu dicek kategorinya.": "transactions this month need their category checked.",
    "Menyimpan berarti: kategori di atas dipakai, dan tanda “perlu ditinjau” dilepas untuk bulan ini.":
        "Saving means: the categories above are applied and the “needs review” mark is cleared for this month.",
    "Semua sudah rapi": "All clean",
    "Semua transaksi sudah berkategori.": "Every transaction has a category.",
    "Tidak ada yang perlu dirapikan.": "Nothing to clean up.",
    "Ubah kategori": "Change category",
    "disarankan": "suggested",
    "disarankan:": "suggested:",
    "sekarang:": "now:",
    "cek": "check",
    "akan ditandai beres": "will be marked done",
    "tidak": "no",

    # --- kantong & aset ---
    "Tambah kantong": "Add pocket",
    "Belum ada kantong tabungan/investasi.": "No savings/investment pocket yet.",
    "Tambahkan lewat": "Add one from",
    "Kalau sudah dipakai transaksi, kantong hanya dinonaktifkan agar riwayat tetap utuh.":
        "Once transactions use it, a pocket is only deactivated so the history stays intact.",
    "Hapus kantong ini?": "Delete this pocket?",
    "Aktif": "Active",
    "Nonaktif": "Inactive",
    "nonaktif": "inactive",
    "Tampil": "Shown",
    "Nilai investasi": "Investment value",
    "Rincian investasi": "Investment breakdown",
    "Belum ada nilai investasi.": "No investment values yet.",
    "Ketuk “+ Perbarui nilai” untuk mengisi.": "Tap “+ Update value” to fill it in.",
    "Perbarui nilai": "Update value",
    "Perbarui bulan ini": "Update this month",
    "Nilai pasar (Rp)": "Market value (Rp)",
    "Simbol": "Symbol",
    "Salin dari": "Copy from",
    "Salin snapshot": "Copy snapshot",
    "salin posisi lalu ubah angkanya": "copy the position, then adjust the numbers",
    "Ke bulan": "To month",
    "snapshot": "snapshot",
    "snapshot bulanan": "monthly snapshot",
    "belum ada snapshot": "no snapshot yet",
    "isi snapshot": "fill in a snapshot",
    "belum diperbarui": "not updated",
    "nilai pasar vs modal yang disetor": "market value vs money paid in",
    "modal": "paid in",
    "dihitung dari mutasi transfer": "computed from transfers",
    "Setoran modal ke sekuritas/exchange dicatat sebagai": "Money paid into a broker/exchange is recorded as",
    ", bukan\n    pengeluaran. Selisih nilai pasar dengan modal itulah untung/rugi yang tampil di atas.":
        ", not an\n    expense. The gap between market value and money paid in is the gain/loss shown above.",
    "; selisihnya dengan modal yang kamu setor adalah untung/rugi.":
        "; the gap against the money you paid in is your gain or loss.",
    "Uang yang pindah antar kantong dicatat sebagai": "Money moving between pockets is recorded as",
    "— menabung, setor dana darurat, atau isi ulang\n    kantong belanja tidak dihitung sebagai pengeluaran. Nilai kantong investasi diambil dari":
        "— saving, topping up the emergency fund or refilling a\n    spending pocket is not counted as expense. An investment pocket's value comes from its",
    "(dipakai untuk": "(used for",
    "(tabungan": "(savings",
    ", investasi": ", investments",
    "· termasuk kas jadi": "· with cash that makes",

    # --- setelan ---
    "ketuk untuk mengubah": "tap to edit",
    "ketuk untuk mengubah nama, urutan, atau menandai cicilan":
        "tap to rename, reorder, or mark as debt",
    "Hitung sebagai cicilan/utang": "Count as debt/instalment",
    "dipakai di rasio cicilan pada laporan bulanan": "used for the debt ratio in the monthly report",
    "Kategori bertanda": "Categories marked",
    "dipakai menghitung rasio cicilan terhadap pemasukan di laporan bulanan.\n  Kategori":
        "are used to compute the debt-to-income ratio in the monthly report.\n  A",
    "tidak bisa dihapus karena dipakai sebagai penampung saat kategori lain dihapus.":
        "category cannot be deleted; it catches transactions when another category is removed.",
    "cicilan": "debt",
    "bawaan": "built-in",
    "disembunyikan": "hidden",
    "Sembunyikan": "Hide",
    "Hapus kategori ini?": "Delete this category?",
    "Transaksi yang memakainya dipindah ke kategori “Lainnya” dan ditandai untuk ditinjau.":
        "Transactions using it move to the “Other” category and get marked for review.",
    "+ Kategori": "+ Category",
    "Template rutin": "Recurring templates",
    "dipakai “Isi bulan ini” · geser kiri untuk hapus": "used by “Fill this month” · swipe left to delete",
    "+ Tambah template": "+ Add template",
    "Belum ada template.": "No templates yet.",
    "Tambahkan KPR, tagihan kartu, gaji — hal yang berulang tiap bulan.":
        "Add the mortgage, card bill, salary — whatever repeats every month.",
    "Template dihapus; entri yang sudah dibuat tidak ikut terhapus.":
        "The template is deleted; entries already created stay.",
    "Atur templatenya di": "Manage the templates in",
    "Buku": "Book",
    "kantong & saldo awal diatur di": "pockets & opening balances live in",
    "Bulan pertama yang dicatat": "First month on record",
    "Backup & ekspor": "Backup & export",
    "data Anda, milik Anda": "your data, yours to keep",
    "Unduh backup": "Download backup",
    "file .db lengkap, bisa dipulihkan": "the full .db file, restorable",
    "Ekspor Excel": "Export to Excel",
    "ringkasan + satu sheet per bulan": "summary + one sheet per month",
    "Akun": "Account",
    "satu pengguna": "single user",
    "password tersimpan terenkripsi di database": "password stored hashed in the database",
    "Ganti password": "Change password",
    "Password saat ini": "Current password",
    "Password baru": "New password",
    "Ulangi": "Repeat",
    "Simpan password": "Save password",
    "Password diperbarui.": "Password updated.",
    "Password saat ini salah.": "Current password is wrong.",
    "Password baru minimal 6 karakter dan harus sama dengan konfirmasi.":
        "The new password needs at least 6 characters and must match the confirmation.",
    "Bahasa": "Language",
    "dipakai di seluruh aplikasi": "used across the whole app",

    # --- konfirmasi hapus & validasi (dipakai JS) ---
    "Hapus entri ini?": "Delete this entry?",
    "Entri dihapus dari bulan ini.": "The entry is removed from this month.",
    "wajib diisi": "required",
    "Jumlah wajib diisi": "Amount is required",
    "Jumlah harus lebih dari 0": "Amount must be greater than 0",
    "Password wajib diisi": "Password is required",
    "Nama wajib diisi": "Name is required",
    "Simbol wajib diisi": "Symbol is required",
    "Kategori wajib diisi": "Category is required",
    "Kolom ini": "This field",
    "Ada kolom wajib (*) yang belum diisi": "A required field (*) is still empty",
    "{n} kolom wajib (*) belum diisi": "{n} required fields (*) are still empty",
    "Tidak ada hasil": "No results",
    "Kosongkan": "Clear",
    "Hari ini": "Today",
    "Bulan ini": "This month",
    "Sebelumnya": "Previous",
    "Berikutnya": "Next",
    # --- potongan kalimat & sisa ---
    "% dari pemasukan)": "% of income)",
    "%) vs bulan lalu": "%) vs last month",
    ", keluar": ", out",
    ", pengeluaran": ", expense",
    ": masuk": ": in",
    "Catatan": "Note",
    "Sisa": "Left",
    "sisa kas": "cash left",
    "dana darurat": "emergency fund",
    "transfer": "transfer",
    "Sisa impor dari spreadsheet. Aplikasi sudah menyiapkan tebakan — kamu tinggal memeriksa.":
        "Left over from the spreadsheet import. The app has prepared a guess — you only need to check it.",
    "pemasukan": "income",
    "pengeluaran": "expense",
    "masuk": "in",
    "keluar": "out",
    "nilai pasar": "market value",
    "Selisih (hasil cari)": "Difference (search result)",
    "Tidak ada yang cocok.": "Nothing matched.",
    "Belum ada transaksi bulan ini.": "No transactions this month.",
    "Coba kata lain.": "Try another word.",
    "Pilih bulan lain di atas.": "Pick another month above.",
    # label tipe kantong
    "Kas & rekening harian": "Cash & everyday accounts",
    "Tabungan & dana darurat": "Savings & emergency fund",
    "Kartu kredit & paylater": "Credit cards & paylater",
    "Investasi": "Investments",
    # --- laporan bulanan (dirakit di report.py) ---
    "Masuk {inc}, keluar {exp} — sisa {net} ({rate}% dari pemasukan).":
        "In {inc}, out {exp} — {net} left ({rate}% of income).",
    "Masuk {inc}, keluar {exp} — defisit {net}, ditutup dari saldo atau dana darurat.":
        "In {inc}, out {exp} — a {net} shortfall, covered from your balance or emergency fund.",
    "{v} dipindahkan ke tabungan/investasi.": "{v} moved into savings/investments.",
    "{v} ditarik dari tabungan/investasi.": "{v} pulled out of savings/investments.",
    "Tingkat menabung": "Savings rate",
    "pemasukan dikurangi pengeluaran": "income minus expense",
    " — patokan sehat 20%": " — a healthy mark is 20%",
    "Rasio cicilan": "Debt ratio",
    "{v} cicilan & tagihan kartu": "{v} in instalments & card bills",
    " — di atas batas sehat {pct}%": " — above the healthy limit of {pct}%",
    "Cakupan dana darurat": "Emergency fund cover",
    "bln": "mo",
    "{fund} dibanding belanja rata-rata {avg}/bln": "{fund} against average spending of {avg}/mo",
    "naik {v} dari bulan lalu": "up {v} from last month",
    "turun {v} dari bulan lalu": "down {v} from last month",
    "{name} {value}, naik {delta} dari rata-rata {n} bulan ({avg}).":
        "{name} {value}, up {delta} from the {n}-month average ({avg}).",
    "{name} menyerap {pct}% pengeluaran bulan ini ({value}).":
        "{name} takes {pct}% of this month's spending ({value}).",
    "Pengeluaran terbesar: {desc} {value}.": "Largest expense: {desc} {value}.",
    "{v} masih bertanda belum dibayar.": "{v} is still marked unpaid.",
    "{n} transaksi senilai {v} belum berkategori atau masih bertanda perlu dicek — laporan ini ikut melenceng selama itu dibiarkan.":
        "{n} transactions worth {v} have no category or are still flagged for review — this report stays off until they are sorted.",
    "Cicilan & tagihan kartu {pct}% dari pemasukan ({v}). Di atas 35% ruang gerak bulanan jadi sempit.":
        "Instalments & card bills are {pct}% of income ({v}). Above 35% the month gets tight.",
    "Dana darurat menutup {n} bulan belanja. Idealnya {target} bulan ({v}).":
        "The emergency fund covers {n} months of spending. Aim for {target} months ({v}).",
    "Dana darurat sudah menutup {n} bulan belanja. Setoran berikutnya lebih berguna diarahkan ke investasi.":
        "The emergency fund already covers {n} months of spending. The next deposit is better aimed at investments.",
    "Pengeluaran melebihi pemasukan {v} bulan ini. Tiga kategori teratas: {list}.":
        "Spending exceeded income by {v} this month. Top three categories: {list}.",
    "Nilai {pots} belum diperbarui untuk bulan ini, jadi total aset memakai angka lama.":
        "{pots} has no updated value this month, so total assets still use the old figure.",
    "Tanpa kategori": "No category",
    "baru saja": "just now",
    # --- halaman login: sapaan & cuaca ---
    "Selamat pagi.": "Good morning.",
    "Selamat siang.": "Good afternoon.",
    "Selamat sore.": "Good evening.",
    "Selamat malam.": "Good night.",
    "pagi": "morning",
    "siang": "midday",
    "senja": "dusk",
    "malam": "night",
    "hujan": "rain",
    "cerah": "clear",
    "cerah berawan": "mostly clear",
    "berawan sebagian": "partly cloudy",
    "mendung": "overcast",
    "berkabut": "foggy",
    "gerimis": "drizzle",
    "hujan ringan": "light rain",
    "hujan lebat": "heavy rain",
    "salju": "snow",
    "hujan lokal": "rain showers",
    "hujan deras": "downpour",
    "badai petir": "thunderstorm",
    "Ganti bahasa": "Switch language",
    # --- masuk dengan Google ---
    "Masuk dengan Google": "Sign in with Google",
    "atau": "or",
    "Gagal masuk lewat Google. Coba lagi.": "Google sign-in failed. Try again.",
    "Akun Google itu tidak diizinkan masuk.": "That Google account is not allowed in.",
    "Pengaturan Google disimpan.": "Google settings saved.",
    "Daftarkan URI berikut di Google Cloud Console → Credentials → OAuth client (Web application) → Authorized redirect URIs.":
        "Register this URI in Google Cloud Console → Credentials → OAuth client (Web application) → Authorized redirect URIs.",
    "Client ID": "Client ID",
    "Client Secret": "Client secret",
    "tersimpan — isi hanya bila ingin mengganti": "stored — fill only to replace it",
    "GOCSPX-…": "GOCSPX-…",
    "Email yang boleh masuk": "Emails allowed in",
    "Hanya email di daftar ini yang bisa masuk, dan semuanya melihat buku yang sama. Password tetap bisa dipakai sebagai cadangan.":
        "Only the emails on this list can sign in, and they all see the same book. The password still works as a fallback.",
    "Terlalu banyak percobaan. Coba lagi dalam {n} menit.": "Too many attempts. Try again in {n} minutes.",
    "Sesi berakhir": "Session expired",
    "Masukkan password untuk melanjutkan. Halaman ini tetap terbuka.":
        "Enter your password to continue. This page stays open.",
    "Ke halaman login": "Go to login page",
    "Buka": "Unlock",
    # --- multi-pengguna ---
    "pemilik": "owner",
    "pengguna": "user",
    "Pengguna": "Users",
    "akun": "accounts",
    "masuk dengan password": "signed in with password",
    "buku sendiri": "own book",
    "terakhir": "last",
    "Nonaktifkan": "Deactivate",
    "Aktifkan": "Activate",
    "Izinkan pendaftaran baru lewat Google": "Allow new sign-ups with Google",
    "Kalau dimatikan, hanya email yang sudah terdaftar yang bisa masuk.":
        "When off, only accounts that already exist can sign in.",
    "Setiap orang yang mendaftar lewat Google mendapat bukunya sendiri — data keuangan Anda tidak ikut terlihat. Email di daftar izin (di bawah) adalah pengecualian: mereka masuk ke buku Anda.":
        "Anyone who signs up with Google gets their own book — your finances stay out of sight. The allowlist below is the exception: those emails open your book.",
    "Akun ini dinonaktifkan.": "This account has been deactivated.",
    "Pendaftaran baru sedang ditutup.": "New sign-ups are closed right now.",
    "Email di daftar ini masuk ke buku Anda (mis. pasangan). Email lain yang mendaftar mendapat buku kosong sendiri.":
        "Emails on this list open your book (e.g. your partner). Anyone else who signs up gets their own empty book.",
    "Lanjutkan dengan Google": "Continue with Google",
    "Masuk dengan password": "Sign in with a password",
    "Pertama kali masuk? Akun dibuat otomatis, lengkap dengan buku kosong Anda sendiri.":
        "First time here? Your account is created automatically, with an empty book of your own.",
    "Akun ini dinonaktifkan. Hubungi pemilik aplikasi.": "This account has been deactivated. Contact the app owner.",
    # --- halaman legal ---
    "Kebijakan Privasi": "Privacy Policy",
    "Persyaratan Layanan": "Terms of Service",
    "diperbarui": "updated",
    "Data apa yang disimpan": "What is stored",
    "Di mana disimpan": "Where it is stored",
    "Apa yang tidak dilakukan": "What this app does not do",
    "Cookie": "Cookies",
    "Menghapus data Anda": "Deleting your data",
    "Layanan apa ini": "What this service is",
    "Tanggung jawab Anda": "Your responsibilities",
    "Angka di aplikasi ini bukan nasihat keuangan": "The numbers here are not financial advice",
    "Cadangan data": "Backups",
    "Penghentian akun": "Ending your account",
    "Dari Google, aplikasi hanya menerima <b>alamat email</b> dan <b>nama</b> Anda. Tidak ada akses ke Gmail, Drive, Kontak, atau layanan Google lain — izin yang diminta hanya <code>openid</code>, <code>email</code>, dan <code>profile</code>.":
        "From Google, the app receives only your <b>email address</b> and <b>name</b>. It has no access to Gmail, Drive, Contacts or any other Google service — the only scopes requested are <code>openid</code>, <code>email</code> and <code>profile</code>.",
    "Selebihnya adalah data yang Anda masukkan sendiri: transaksi, kategori, kantong, nilai aset, dan catatan bulanan.":
        "Everything else is what you enter yourself: transactions, categories, pockets, asset values and monthly notes.",
    "Di satu server di Singapura (Fly.io), dalam <b>file database terpisah milik Anda sendiri</b>. Pengguna lain memakai file yang berbeda, jadi catatan keuangan Anda tidak pernah tercampur dan tidak terlihat oleh pengguna lain.":
        "On a single server in Singapore (Fly.io), in <b>a separate database file of your own</b>. Other users get different files, so your records never mix with theirs and are not visible to them.",
    "Pemilik aplikasi dapat mengelola akun (menonaktifkan, menghapus) dan secara teknis memiliki akses ke server tempat file itu berada. Kalau itu tidak Anda inginkan, jangan memasukkan data yang sensitif bagi Anda.":
        "The app owner can manage accounts (deactivate, delete) and technically has access to the server holding those files. If that is not acceptable to you, do not enter data you consider sensitive.",
    "Tidak ada iklan, tidak ada pelacak pihak ketiga, tidak ada analitik. Data Anda tidak dijual, tidak dibagikan, dan tidak dikirim ke layanan lain. Satu-satunya panggilan keluar adalah ke Google saat Anda masuk, dan ke layanan cuaca terbuka (Open-Meteo) untuk menampilkan cuaca di halaman masuk.":
        "No ads, no third-party trackers, no analytics. Your data is not sold, shared or sent anywhere else. The only outbound calls are to Google when you sign in, and to an open weather service (Open-Meteo) to show the weather on the sign-in page.",
    "Satu cookie sesi bertanda tangan supaya Anda tetap masuk selama 30 hari, dan penyimpanan lokal peramban untuk pilihan tema terang/gelap. Tidak ada cookie iklan.":
        "One signed session cookie so you stay signed in for 30 days, plus browser local storage for your light/dark preference. No advertising cookies.",
    "Buka Setelan → Akun → Hapus akun. File database Anda dihapus dari server saat itu juga, beserta seluruh isinya. Tindakan ini tidak bisa dibatalkan. Sebelum menghapus, Anda bisa mengunduh salinan lengkap lewat Setelan → Backup & ekspor.":
        "Go to Settings → Account → Delete account. Your database file is removed from the server immediately, with everything in it. This cannot be undone. Before deleting, you can download a full copy from Settings → Backup & export.",
    "Pertanyaan atau permintaan lain bisa dikirim ke {email}.": "Any other question or request can be sent to {email}.",
    "Monetary adalah aplikasi pencatat keuangan pribadi yang dibuat dan dijalankan oleh satu orang, gratis, dan disediakan apa adanya (<i>as is</i>). Tidak ada jaminan ketersediaan, dan bisa berubah atau berhenti kapan saja.":
        "Monetary is a personal finance tracker built and run by one person, free of charge, provided <i>as is</i>. There is no uptime guarantee, and it may change or stop at any time.",
    "Anda bertanggung jawab atas isi catatan Anda sendiri dan atas keamanan akun Google yang dipakai masuk. Jangan memakai aplikasi ini untuk hal yang melanggar hukum.":
        "You are responsible for the content of your own records and for the security of the Google account you sign in with. Do not use this app for anything unlawful.",
    "Ringkasan, indikator kesehatan, dan saran dihitung dengan aturan sederhana dari angka yang Anda masukkan sendiri. Gunakan sebagai alat bantu, bukan sebagai nasihat keuangan, pajak, atau investasi.":
        "Summaries, health indicators and suggestions are computed with simple rules from the numbers you enter. Treat them as a tool, not as financial, tax or investment advice.",
    "Server membuat snapshot volume harian, tetapi itu bukan jaminan. Unduh cadangan Anda sendiri secara berkala lewat Setelan → Backup & ekspor.":
        "The server takes daily volume snapshots, but that is not a guarantee. Download your own backup regularly from Settings → Backup & export.",
    "Anda bisa menghapus akun kapan saja lewat Setelan → Akun. Pemilik aplikasi dapat menonaktifkan akun yang menyalahgunakan layanan.":
        "You can delete your account at any time from Settings → Account. The app owner may deactivate accounts that abuse the service.",
    # --- hapus akun ---
    "Hapus akun": "Delete account",
    "Hapus akun saya": "Delete my account",
    "Hapus akun dan semua data?": "Delete your account and all data?",
    "File database Anda dihapus permanen. Tidak bisa dibatalkan.": "Your database file is deleted for good. This cannot be undone.",
    "Akun dan seluruh catatan keuangan Anda dihapus dari server saat itu juga, dan tidak bisa dikembalikan. Unduh cadangan dulu lewat Backup & ekspor kalau perlu.":
        "Your account and all of your records are removed from the server immediately and cannot be restored. Download a backup first from Backup & export if you need one.",
    "Akun dan seluruh datanya sudah dihapus.": "The account and all of its data have been deleted.",
    # --- pendaftaran email + password ---
    "Buat akun": "Create account",
    "buku kosong milik Anda sendiri": "an empty book of your own",
    "Email": "Email",
    "Ulangi": "Repeat",
    "mis. John": "e.g. John",
    "atau pakai email": "or use email",
    "Alamat email tidak valid.": "That email address is not valid.",
    "Password minimal 8 karakter dan harus sama dengan konfirmasi.":
        "Password must be at least 8 characters and match the confirmation.",
    "Email itu sudah terdaftar. Masuk saja.": "That email is already registered. Just sign in.",
    "Minimal 8 karakter. Email tidak kami verifikasi lewat surel — kalau suatu saat Anda masuk dengan Google memakai email yang sama, akun ini otomatis jadi milik akun Google itu.":
        "At least 8 characters. We do not verify the address by email — if you later sign in with Google using the same address, this account becomes that Google account's.",
    "Sudah punya akun? Masuk": "Already have an account? Sign in",
    "Belum punya akun? Daftar": "No account yet? Sign up",
    "Dengan mendaftar Anda setuju pada": "By signing up you agree to the",
    "dan": "and the",
    "Atur password": "Set a password",
    "Akun ini masuk lewat Google. Menambah password memberi Anda pintu cadangan.":
        "This account signs in with Google. Adding a password gives you a fallback door.",
    "Password baru minimal 8 karakter dan harus sama dengan konfirmasi.":
        "The new password needs at least 8 characters and must match the confirmation.",
    # --- superadmin ---
    "superadmin": "superadmin",
    "Akun superadmin": "Superadmin account",
    "Email superadmin": "Superadmin email",
    "Hanya email ini yang memegang buku utama beserta seluruh setelan aplikasi. Email lain — termasuk yang ada di daftar izin — masuk sebagai pengguna biasa.":
        "Only this email holds the main book and every app-level setting. Any other email — including those on the allowlist — signs in as a regular user.",
    "Batas jumlah akun": "Account limit",
    "Pendaftaran otomatis berhenti setelah batas ini tercapai.": "Sign-ups stop automatically once this limit is reached.",
    "Pengaturan admin disimpan.": "Admin settings saved.",
    "Izinkan pendaftaran baru": "Allow new sign-ups",
    "Kalau dimatikan, hanya akun yang sudah ada yang bisa masuk.": "When off, only existing accounts can sign in.",
    "Setiap orang yang mendaftar mendapat bukunya sendiri — data keuangan Anda tidak ikut terlihat. Mereka hanya bisa mengurus bukunya sendiri: tidak bisa melihat daftar pengguna, mengubah konfigurasi Google, atau menyentuh setelan aplikasi.":
        "Everyone who signs up gets their own book — your finances stay out of sight. They can only manage their own book: no user list, no Google settings, nothing app-level.",
    "transaksi perlu dicek": "transactions need a check",
    # --- lupa password & verifikasi email ---
    "Lupa password": "Forgot password",
    "Lupa password?": "Forgot your password?",
    "kami kirim tautan ke email Anda": "we will email you a link",
    "Kalau alamat itu terdaftar, tautan setel ulang sudah dikirim. Cek juga folder spam.":
        "If that address is registered, a reset link is on its way. Check your spam folder too.",
    "Kembali ke halaman masuk": "Back to sign in",
    "Terlalu banyak percobaan. Coba lagi nanti.": "Too many attempts. Try again later.",
    "Pengiriman surel belum diatur di aplikasi ini. Hubungi pemilik aplikasi.":
        "Email sending is not set up on this app. Contact the app owner.",
    "Kirim tautan": "Send the link",
    "Email Anda sudah terverifikasi.": "Your email is verified.",
    "Setel password baru": "Set a new password",
    "setelah ini Anda langsung masuk": "you will be signed in right after",
    "Semua sesi lama di perangkat lain otomatis keluar.": "Every old session on other devices is signed out.",
    "Email belum diverifikasi.": "Email not verified yet.",
    "Kirim ulang tautan": "Resend the link",
    "Tautan verifikasi dikirim. Cek kotak masuk Anda.": "Verification link sent. Check your inbox.",
    "Pengiriman surel belum diatur.": "Email sending is not set up.",
    "Tautannya sudah tidak berlaku. Minta yang baru.": "That link is no longer valid. Request a new one.",
    # panel surel
    "Pengiriman surel": "Email delivery",
    "Pengaturan surel disimpan.": "Email settings saved.",
    "Surel uji terkirim.": "Test email sent.",
    "Surel uji gagal terkirim. Periksa API key dan alamat pengirim.":
        "The test email failed. Check the API key and sender address.",
    "Dipakai untuk verifikasi email dan tautan setel ulang password. Tanpa ini, pengguna yang lupa password tidak punya jalan pulih.":
        "Used for email verification and password reset links. Without it, a user who forgets their password has no way back in.",
    "Resend API key": "Resend API key",
    "Alamat pengirim": "Sender address",
    "Nama pengirim": "Sender name",
    "Domain pengirim harus sudah diverifikasi di Resend (SPF & DKIM di Cloudflare).":
        "The sender domain must be verified in Resend (SPF & DKIM records in Cloudflare).",
    "Kirim surel uji": "Send a test email",
    # isi surel
    "Konfirmasi alamat email Anda": "Confirm your email address",
    "Satu langkah lagi": "One more step",
    "Ketuk tombol di bawah untuk memastikan alamat ini benar milik Anda. Tautan berlaku 3 hari.":
        "Tap the button below to confirm this address is yours. The link works for 3 days.",
    "Kalau Anda tidak merasa mendaftar di Monetary, abaikan saja surel ini.":
        "If you did not sign up for Monetary, simply ignore this email.",
    "Konfirmasi email": "Confirm email",
    "Setel ulang password Monetary": "Reset your Monetary password",
    "Setel ulang password": "Reset your password",
    "Ada permintaan untuk mengatur ulang password akun ini. Tautan di bawah berlaku satu jam dan hanya bisa dipakai sekali.":
        "Someone asked to reset the password for this account. The link below works for one hour and only once.",
    "Kalau bukan Anda yang meminta, abaikan saja — password lama tetap berlaku.":
        "If that was not you, just ignore this — your current password still works.",
    "Surel uji dari Monetary": "Test email from Monetary",
    "Konfigurasi surel berhasil": "Email delivery works",
    "Kalau Anda menerima surel ini, pengiriman dari Monetary sudah jalan.":
        "If you received this, sending email from Monetary is working.",
}
